from enum import StrEnum
from typing import Final
from datetime import datetime

from pydantic import BaseModel, ConfigDict

STOCK_TICK_SECONDS: Final[int] = 60 * 60
MAX_TICKS_PER_INTERACTION: Final[int] = 24
STOCK_HISTORY_DAYS: Final[int] = 7
STOCK_ACTION_TIMEOUT_SECONDS: Final[int] = 180

BCAT_SYMBOL: Final[str] = "BCAT"
BCAT_NAME: Final[str] = "破貓科技股份有限公司"
BCAT_CATEGORY: Final[str] = "迷因科技"
BCAT_INITIAL_PRICE_CENTS: Final[int] = 10_000
BCAT_TOTAL_SHARES: Final[int] = 1_000_000
BCAT_FLOAT_SHARES: Final[int] = 650_000
BCAT_BASE_VOLATILITY_BPS: Final[int] = 70
BCAT_VOLATILITY_AMPLIFIER_BPS: Final[int] = 150
BCAT_LIQUIDITY_SHARES: Final[int] = 25_000
BCAT_MEAN_REVERSION_BPS: Final[int] = 35
BCAT_MAX_TICK_CHANGE_BPS: Final[int] = 450
STOCK_NEWS_CADENCE_HOURS: Final[int] = 8


class StockCompanySeed(BaseModel):
    """Seed profile for one virtual stock company."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    name: str
    category: str
    initial_price_cents: int
    total_shares: int
    float_shares: int
    base_volatility_bps: int
    volatility_amplifier_bps: int
    liquidity_shares: int
    fair_value_cents: int
    mean_reversion_bps: int
    max_tick_change_bps: int
    news_cadence_hours: int = STOCK_NEWS_CADENCE_HOURS


STOCK_COMPANY_SEEDS: Final[tuple[StockCompanySeed, ...]] = (
    StockCompanySeed(
        symbol=BCAT_SYMBOL,
        name=BCAT_NAME,
        category=BCAT_CATEGORY,
        initial_price_cents=BCAT_INITIAL_PRICE_CENTS,
        total_shares=BCAT_TOTAL_SHARES,
        float_shares=BCAT_FLOAT_SHARES,
        base_volatility_bps=BCAT_BASE_VOLATILITY_BPS,
        volatility_amplifier_bps=BCAT_VOLATILITY_AMPLIFIER_BPS,
        liquidity_shares=BCAT_LIQUIDITY_SHARES,
        fair_value_cents=BCAT_INITIAL_PRICE_CENTS,
        mean_reversion_bps=BCAT_MEAN_REVERSION_BPS,
        max_tick_change_bps=BCAT_MAX_TICK_CHANGE_BPS,
    ),
    StockCompanySeed(
        symbol="AURM",
        name="晨曜能源股份有限公司",
        category="再生能源",
        initial_price_cents=8_800,
        total_shares=1_800_000,
        float_shares=1_100_000,
        base_volatility_bps=45,
        volatility_amplifier_bps=110,
        liquidity_shares=60_000,
        fair_value_cents=9_200,
        mean_reversion_bps=45,
        max_tick_change_bps=300,
    ),
    StockCompanySeed(
        symbol="GLBX",
        name="雲港物流控股",
        category="物流運輸",
        initial_price_cents=12_500,
        total_shares=900_000,
        float_shares=520_000,
        base_volatility_bps=35,
        volatility_amplifier_bps=100,
        liquidity_shares=45_000,
        fair_value_cents=12_200,
        mean_reversion_bps=55,
        max_tick_change_bps=260,
    ),
    StockCompanySeed(
        symbol="QBIT",
        name="量子豆資料系統",
        category="雲端資料",
        initial_price_cents=16_000,
        total_shares=700_000,
        float_shares=430_000,
        base_volatility_bps=80,
        volatility_amplifier_bps=140,
        liquidity_shares=28_000,
        fair_value_cents=15_500,
        mean_reversion_bps=30,
        max_tick_change_bps=520,
    ),
    StockCompanySeed(
        symbol="NXTS",
        name="星橋半導體",
        category="半導體",
        initial_price_cents=21_000,
        total_shares=1_200_000,
        float_shares=760_000,
        base_volatility_bps=60,
        volatility_amplifier_bps=125,
        liquidity_shares=55_000,
        fair_value_cents=21_800,
        mean_reversion_bps=40,
        max_tick_change_bps=380,
    ),
)


class StockAction(StrEnum):
    """User-facing stock operation families."""

    BUY = "buy"
    SHORT = "short"


class StockOperationStatus(StrEnum):
    """Lifecycle states for a cross-database stock operation."""

    PENDING = "pending"
    WALLET_APPLIED = "wallet_applied"
    APPLIED = "applied"
    FAILED = "failed"
    RECONCILE_REQUIRED = "reconcile_required"


class StockTradeLegType(StrEnum):
    """Atomic legs generated by one stock operation."""

    OPEN_LONG = "open_long"
    SELL_LONG = "sell_long"
    OPEN_SHORT = "open_short"
    COVER_SHORT = "cover_short"


class StockProfileView(BaseModel):
    """Read-only stock profile and latest quote."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    name: str
    category: str
    price_cents: int
    previous_close_price_cents: int
    day_open_price_cents: int
    total_shares: int
    float_shares: int
    base_volatility_bps: int
    volatility_amplifier_bps: int
    liquidity_shares: int
    fair_value_cents: int
    mean_reversion_bps: int
    max_tick_change_bps: int
    news_cadence_hours: int
    updated_at: datetime


class StockPositionView(BaseModel):
    """Read-only per-user stock position."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    user_id: int
    user_name: str = ""
    long_shares: int = 0
    long_cost_basis: int = 0
    short_shares: int = 0
    short_entry_value: int = 0
    short_collateral: int = 0
    realized_pnl: int = 0


class StockParticipantPositionView(BaseModel):
    """Public stock-level position summary for one participant."""

    model_config = ConfigDict(frozen=True)

    user_id: int
    user_name: str
    long_shares: int
    short_shares: int
    realized_pnl: int


class StockTradeLegView(BaseModel):
    """Read-only stock trade leg for UI and reconciliation."""

    model_config = ConfigDict(frozen=True)

    operation_id: str
    leg_order: int
    symbol: str
    user_id: int
    user_name: str = ""
    leg_type: StockTradeLegType
    shares: int
    price_cents: int
    wallet_delta: int
    basis_delta: int
    collateral_delta: int
    realized_pnl_delta: int
    created_at: datetime


class StockNewsView(BaseModel):
    """Read-only stock news item."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    headline: str
    sentiment_bps: int
    source: str = "template"
    model: str = ""
    expires_at: datetime | None = None
    created_at: datetime


class StockGeneratedNews(BaseModel):
    """Generated stock news payload before persistence."""

    model_config = ConfigDict(frozen=True)

    headline: str
    sentiment_bps: int
    source: str
    model: str = ""


class StockPriceTickView(BaseModel):
    """Read-only stock price tick."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    price_cents: int
    created_at: datetime


class StockMarketQuote(BaseModel):
    """One row in the market list."""

    model_config = ConfigDict(frozen=True)

    profile: StockProfileView
    change_cents: int
    change_bps: int
    pressure_bps: int


class StockDetailViewData(BaseModel):
    """Full personal detail view for one stock."""

    model_config = ConfigDict(frozen=True)

    quote: StockMarketQuote
    balance: int
    position: StockPositionView
    recent_trades: tuple[StockTradeLegView, ...]
    public_positions: tuple[StockParticipantPositionView, ...] = ()
    news: tuple[StockNewsView, ...]
    ticks: tuple[StockPriceTickView, ...]


class StockSettlementResult(BaseModel):
    """Result returned by the one stock settlement helper."""

    model_config = ConfigDict(frozen=True)

    success: bool
    operation_id: str | None
    symbol: str
    requested_action: StockAction
    shares: int
    price_cents: int
    wallet_delta: int
    balance_after: int
    position: StockPositionView
    legs: tuple[StockTradeLegView, ...]
    status: StockOperationStatus | None = None
    error: str = ""


class StockReconciliationOperation(BaseModel):
    """Read-only non-final operation snapshot for manual reconciliation."""

    model_config = ConfigDict(frozen=True)

    operation_id: str
    status: StockOperationStatus
    user_id: int
    user_name: str
    symbol: str
    requested_action: StockAction
    failure_reason: str
    created_at: datetime
    updated_at: datetime
    legs: tuple[StockTradeLegView, ...]


__all__ = [
    "BCAT_BASE_VOLATILITY_BPS",
    "BCAT_CATEGORY",
    "BCAT_FLOAT_SHARES",
    "BCAT_INITIAL_PRICE_CENTS",
    "BCAT_LIQUIDITY_SHARES",
    "BCAT_MAX_TICK_CHANGE_BPS",
    "BCAT_MEAN_REVERSION_BPS",
    "BCAT_NAME",
    "BCAT_SYMBOL",
    "BCAT_TOTAL_SHARES",
    "BCAT_VOLATILITY_AMPLIFIER_BPS",
    "MAX_TICKS_PER_INTERACTION",
    "STOCK_ACTION_TIMEOUT_SECONDS",
    "STOCK_COMPANY_SEEDS",
    "STOCK_HISTORY_DAYS",
    "STOCK_NEWS_CADENCE_HOURS",
    "STOCK_TICK_SECONDS",
    "StockAction",
    "StockCompanySeed",
    "StockDetailViewData",
    "StockGeneratedNews",
    "StockMarketQuote",
    "StockNewsView",
    "StockOperationStatus",
    "StockParticipantPositionView",
    "StockPositionView",
    "StockPriceTickView",
    "StockProfileView",
    "StockReconciliationOperation",
    "StockSettlementResult",
    "StockTradeLegType",
    "StockTradeLegView",
]
