from enum import StrEnum
from typing import Final
from datetime import datetime

from pydantic import BaseModel, ConfigDict

STOCK_TICK_SECONDS: Final[int] = 60 * 60
MAX_TICKS_PER_INTERACTION: Final[int] = 24
STOCK_HISTORY_DAYS: Final[int] = 7
STOCK_ACTION_TIMEOUT_SECONDS: Final[int] = 180

BCAT_SYMBOL: Final[str] = "BCAT"
BCAT_NAME: Final[str] = "破貓股份有限公司"
BCAT_CATEGORY: Final[str] = "迷因科技"
BCAT_INITIAL_PRICE_CENTS: Final[int] = 10_000
BCAT_TOTAL_SHARES: Final[int] = 1_000_000
BCAT_BASE_VOLATILITY_BPS: Final[int] = 70
BCAT_VOLATILITY_AMPLIFIER_BPS: Final[int] = 150


class StockAction(StrEnum):
    """User-facing stock operation families."""

    BUY = "buy"
    SHORT = "short"


class StockOperationStatus(StrEnum):
    """Lifecycle states for a cross-database stock operation."""

    PENDING = "pending"
    STOCK_APPLIED = "stock_applied"
    WALLET_APPLIED = "wallet_applied"
    APPLIED = "applied"
    RECONCILE_REQUIRED = "reconcile_required"
    REVERSED = "reversed"


class StockTradeLegType(StrEnum):
    """Atomic legs generated by one stock operation."""

    OPEN_LONG = "open_long"
    SELL_LONG = "sell_long"
    OPEN_SHORT = "open_short"
    COVER_SHORT = "cover_short"


class StockProfileView(BaseModel):
    """Read-only stock profile and latest quote."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    name: str
    category: str
    price_cents: int
    previous_close_price_cents: int
    day_open_price_cents: int
    total_shares: int
    base_volatility_bps: int
    volatility_amplifier_bps: int
    updated_at: datetime


class StockPositionView(BaseModel):
    """Read-only per-user stock position."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    user_id: int
    user_name: str = ""
    long_shares: int = 0
    long_cost_basis: int = 0
    short_shares: int = 0
    short_entry_value: int = 0
    short_collateral: int = 0
    realized_pnl: int = 0


class StockParticipantPositionView(BaseModel):
    """Public stock-level position summary for one participant."""

    model_config = ConfigDict(frozen=True)

    user_id: int
    user_name: str
    long_shares: int
    short_shares: int
    realized_pnl: int


class StockTradeLegView(BaseModel):
    """Read-only stock trade leg for UI and reconciliation."""

    model_config = ConfigDict(frozen=True)

    operation_id: str
    leg_order: int
    symbol: str
    user_id: int
    user_name: str = ""
    leg_type: StockTradeLegType
    shares: int
    price_cents: int
    wallet_delta: int
    basis_delta: int
    collateral_delta: int
    realized_pnl_delta: int
    created_at: datetime


class StockNewsView(BaseModel):
    """Read-only deterministic stock news item."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    headline: str
    sentiment_bps: int
    created_at: datetime


class StockPriceTickView(BaseModel):
    """Read-only stock price tick."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    price_cents: int
    created_at: datetime


class StockMarketQuote(BaseModel):
    """One row in the market list."""

    model_config = ConfigDict(frozen=True)

    profile: StockProfileView
    change_cents: int
    change_bps: int
    pressure_bps: int


class StockDetailViewData(BaseModel):
    """Full personal detail view for one stock."""

    model_config = ConfigDict(frozen=True)

    quote: StockMarketQuote
    balance: int
    position: StockPositionView
    recent_trades: tuple[StockTradeLegView, ...]
    public_positions: tuple[StockParticipantPositionView, ...] = ()
    news: tuple[StockNewsView, ...]
    ticks: tuple[StockPriceTickView, ...]


class StockSettlementResult(BaseModel):
    """Result returned by the one stock settlement helper."""

    model_config = ConfigDict(frozen=True)

    success: bool
    operation_id: str | None
    symbol: str
    requested_action: StockAction
    shares: int
    price_cents: int
    wallet_delta: int
    balance_after: int
    position: StockPositionView
    legs: tuple[StockTradeLegView, ...]
    status: StockOperationStatus | None = None
    error: str = ""


class StockReconciliationOperation(BaseModel):
    """Read-only non-final operation snapshot for manual reconciliation."""

    model_config = ConfigDict(frozen=True)

    operation_id: str
    status: StockOperationStatus
    user_id: int
    symbol: str
    requested_action: StockAction
    failure_reason: str
    created_at: datetime
    updated_at: datetime
    legs: tuple[StockTradeLegView, ...]


__all__ = [
    "BCAT_BASE_VOLATILITY_BPS",
    "BCAT_CATEGORY",
    "BCAT_INITIAL_PRICE_CENTS",
    "BCAT_NAME",
    "BCAT_SYMBOL",
    "BCAT_TOTAL_SHARES",
    "BCAT_VOLATILITY_AMPLIFIER_BPS",
    "MAX_TICKS_PER_INTERACTION",
    "STOCK_ACTION_TIMEOUT_SECONDS",
    "STOCK_HISTORY_DAYS",
    "STOCK_TICK_SECONDS",
    "StockAction",
    "StockDetailViewData",
    "StockMarketQuote",
    "StockNewsView",
    "StockOperationStatus",
    "StockParticipantPositionView",
    "StockPositionView",
    "StockPriceTickView",
    "StockProfileView",
    "StockReconciliationOperation",
    "StockSettlementResult",
    "StockTradeLegType",
    "StockTradeLegView",
]
